// <auto-generated />
using System;
using Infotecs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infotecs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infotecs.Models.FileEntity", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uid");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Infotecs.Models.ResultEntity", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<decimal>("AvgValue")
                        .HasColumnType("numeric");

                    b.Property<int>("DateTimeDelta")
                        .HasColumnType("integer");

                    b.Property<Guid>("FileUid")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MedianValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("MinDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric");

                    b.HasKey("Uid");

                    b.HasIndex("FileUid")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Infotecs.Models.ValueEntity", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("FileUid")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Uid");

                    b.HasIndex("FileUid");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Infotecs.Models.ResultEntity", b =>
                {
                    b.HasOne("Infotecs.Models.FileEntity", "File")
                        .WithOne("Result")
                        .HasForeignKey("Infotecs.Models.ResultEntity", "FileUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Infotecs.Models.ValueEntity", b =>
                {
                    b.HasOne("Infotecs.Models.FileEntity", "File")
                        .WithMany("Values")
                        .HasForeignKey("FileUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Infotecs.Models.FileEntity", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
