//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infotecs.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infotecs.Shared.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти файл с указанным названием..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата не может быть позже текущей и раньше 01.01.2000.
        /// </summary>
        internal static string InvalidDateTimeRange {
            get {
                return ResourceManager.GetString("InvalidDateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время выполнения не может быть меньше 0..
        /// </summary>
        internal static string InvalidExecutionTimeRange {
            get {
                return ResourceManager.GetString("InvalidExecutionTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение показателя не может быть меньше 0..
        /// </summary>
        internal static string InvalidValueRange {
            get {
                return ResourceManager.GetString("InvalidValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти значений по названию файла..
        /// </summary>
        internal static string LastValuesNotFound {
            get {
                return ResourceManager.GetString("LastValuesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В файле должно быть от 1 до 10.000 строк.
        /// </summary>
        internal static string LineLimitError {
            get {
                return ResourceManager.GetString("LineLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В строке {0} указан неверный формат даты и времени. Правильный формат - &quot;ГГГГ-ММ-ДДTчч-мм-сс.ммммZ&quot;.
        /// </summary>
        internal static string WrongDateTimeFormat {
            get {
                return ResourceManager.GetString("WrongDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В строке {0} неверно задано время выполнения..
        /// </summary>
        internal static string WrongExecutionTimeFormat {
            get {
                return ResourceManager.GetString("WrongExecutionTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат файла или файл пуст..
        /// </summary>
        internal static string WrongFileError {
            get {
                return ResourceManager.GetString("WrongFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В строке {0} неверно указано значение..
        /// </summary>
        internal static string WrongValueFormat {
            get {
                return ResourceManager.GetString("WrongValueFormat", resourceCulture);
            }
        }
    }
}
